// Generated by tools/generate.mjs. Do not edit by hand.

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct AddSshAuthorizedKeyInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "publicKey")]
    pub public_key: String,
    /// SSH User ID
    #[serde(rename = "sshUserId")]
    pub ssh_user_id: String,
}

/// An enumeration.
#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum AppAliasSortBy {
    #[default]
    #[serde(rename = "NEWEST")]
    Newest,
    #[serde(rename = "OLDEST")]
    Oldest,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct AppCdnCacheConfigUpdate {
    #[serde(rename = "enabled", default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct AppDomainRedirectRules {
    /// Type of redirection; sets the http code appropriately.
    #[serde(rename = "httpCode")]
    pub http_code: HTTPRedirectType,
    /// Domain to redirect to.
    #[serde(rename = "to")]
    pub to: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct AutobuildDeploymentExtraData {
    #[serde(rename = "wordpress", default, skip_serializing_if = "Option::is_none")]
    pub wordpress: Option<WordpressDeploymentExtraData>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct ConnectGithubRepoToAppInput {
    /// The ID of the App
    #[serde(rename = "appId")]
    pub app_id: String,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// The branch to deploy from
    #[serde(
        rename = "deployBranch",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub deploy_branch: Option<String>,
    /// The ID of the Github app repository installation
    #[serde(rename = "installationRepoId")]
    pub installation_repo_id: String,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum CountComparison {
    #[default]
    #[serde(rename = "EQUAL")]
    Equal,
    #[serde(rename = "GREATER_THAN")]
    GreaterThan,
    #[serde(rename = "GREATER_THAN_OR_EQUAL")]
    GreaterThanOrEqual,
    #[serde(rename = "LESS_THAN")]
    LessThan,
    #[serde(rename = "LESS_THAN_OR_EQUAL")]
    LessThanOrEqual,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct CountFilter {
    #[serde(
        rename = "comparison",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub comparison: Option<CountComparison>,
    #[serde(rename = "count", default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct CreateAppDBInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// App ID
    #[serde(rename = "id")]
    pub id: String,
    /// Database name
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct CreateAppDatabaseInput {
    /// App ID.
    #[serde(rename = "appId")]
    pub app_id: String,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// Database engine to provision and link to the app.
    #[serde(rename = "dbEngine")]
    pub db_engine: DatabaseEngine,
    /// Database name.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct CreateAppVolumeInput {
    /// App ID
    #[serde(rename = "appId")]
    pub app_id: String,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// Volume max size in bytes
    #[serde(
        rename = "maxSizeBytes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_size_bytes: Option<i64>,
    /// Volume mount path
    #[serde(rename = "mountPath")]
    pub mount_path: String,
}

/// Create a new `Api`-sourced unified cronjob on an app.
///
/// Exactly one of `fetch` / `execute` must be provided; that choice fixes the
/// cronjob's (immutable) kind.
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct CreateCronJobInput {
    /// The app the cronjob belongs to.
    #[serde(rename = "appId")]
    pub app_id: String,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// Whether the cronjob is enabled. Defaults to `true`.
    #[serde(rename = "enabled", default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "execute", default, skip_serializing_if = "Option::is_none")]
    pub execute: Option<ExecuteCronJobTargetInput>,
    #[serde(rename = "fetch", default, skip_serializing_if = "Option::is_none")]
    pub fetch: Option<FetchCronJobTargetInput>,
    #[serde(
        rename = "maxRetries",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_retries: Option<i32>,
    #[serde(
        rename = "maxScheduleDrift",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_schedule_drift: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "schedule")]
    pub schedule: String,
    #[serde(rename = "timeout", default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

/// Predicates applied to a cronjob listing. Unset fields are not restricted.
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct CronJobFilter {
    /// `true` returns only enabled cronjobs, `false` only disabled ones.
    #[serde(rename = "enabled", default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Restrict to platform-managed (`true`) or user-owned (`false`) cronjobs.
    #[serde(rename = "isManaged", default, skip_serializing_if = "Option::is_none")]
    pub is_managed: Option<bool>,
    /// Restrict to fetch or execute cronjobs. Takes precedence over the
    /// deprecated top-level `kind` argument.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<CronJobKind>,
    /// Case-insensitive substring match on the cronjob name.
    #[serde(
        rename = "nameContains",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub name_contains: Option<String>,
    /// Restrict by where the cronjob was defined.
    #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
    pub source: Option<CronJobSource>,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum CronJobKind {
    #[default]
    #[serde(rename = "EXECUTE")]
    Execute,
    #[serde(rename = "FETCH")]
    Fetch,
}

/// Field a cronjob listing is ordered by. Ties are broken by insertion order so
/// pagination cursors stay stable.
#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum CronJobOrderBy {
    #[default]
    #[serde(rename = "CREATED_AT")]
    CreatedAt,
    #[serde(rename = "ID")]
    Id,
    #[serde(rename = "NAME")]
    Name,
    #[serde(rename = "UPDATED_AT")]
    UpdatedAt,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum CronJobSortDirection {
    #[default]
    #[serde(rename = "ASC")]
    Asc,
    #[serde(rename = "DESC")]
    Desc,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum CronJobSource {
    #[default]
    #[serde(rename = "API")]
    Api,
    #[serde(rename = "CONFIG")]
    Config,
    #[serde(rename = "PROVISIONED")]
    Provisioned,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DNSCAAExtraInput {
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "tag")]
    pub tag: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DNSMXExtraInput {
    #[serde(rename = "preference")]
    pub preference: i32,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DNSRecordUpdate {
    #[serde(rename = "caa", default, skip_serializing_if = "Option::is_none")]
    pub caa: Option<DNSCAAExtraInput>,
    /// Whether the DNS record should be deleted instead of upserted.
    #[serde(rename = "delete", default, skip_serializing_if = "Option::is_none")]
    pub delete: Option<bool>,
    /// ID of the DNS record to update or delete.
    #[serde(rename = "id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Record kind. Required when creating/upserting by name or deleting by natural key.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<RecordKind>,
    #[serde(rename = "mx", default, skip_serializing_if = "Option::is_none")]
    pub mx: Option<DNSMXExtraInput>,
    /// Record owner/name within the DNS domain.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "soa", default, skip_serializing_if = "Option::is_none")]
    pub soa: Option<DNSSOAExtraInput>,
    #[serde(rename = "srv", default, skip_serializing_if = "Option::is_none")]
    pub srv: Option<DNSSRVExtraInput>,
    #[serde(rename = "sshfp", default, skip_serializing_if = "Option::is_none")]
    pub sshfp: Option<DNSSSHFPExtraInput>,
    /// Time to live in seconds.
    #[serde(rename = "ttl", default, skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// Record value. Required when creating/upserting by name.
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum DNSRecordsSortBy {
    #[default]
    #[serde(rename = "NEWEST")]
    Newest,
    #[serde(rename = "OLDEST")]
    Oldest,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DNSSOAExtraInput {
    #[serde(rename = "expire")]
    pub expire: i32,
    #[serde(rename = "minimum")]
    pub minimum: i32,
    #[serde(rename = "mname")]
    pub mname: String,
    #[serde(rename = "refresh")]
    pub refresh: i32,
    #[serde(rename = "retry")]
    pub retry: i32,
    #[serde(rename = "rname")]
    pub rname: String,
    #[serde(rename = "serial")]
    pub serial: i32,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DNSSRVExtraInput {
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "service")]
    pub service: String,
    #[serde(rename = "weight")]
    pub weight: i32,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DNSSSHFPExtraInput {
    #[serde(rename = "algorithm")]
    pub algorithm: i32,
    #[serde(rename = "type")]
    pub r#type: i32,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum DatabaseEngine {
    #[default]
    #[serde(rename = "MYSQL")]
    Mysql,
    #[serde(rename = "POSTGRES")]
    Postgres,
    #[serde(rename = "SQLITE")]
    Sqlite,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeleteAppDBInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// App Database ID
    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeleteAppDomainInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// ID of the domain to delete.
    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeleteAppInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// App ID to delete.
    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeleteAppVolumeInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// App Volume ID
    #[serde(rename = "id")]
    pub id: String,
}

/// Delete an `Api`-sourced unified cronjob.
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeleteCronJobInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// CronJob ID.
    #[serde(rename = "cronJobId")]
    pub cron_job_id: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeleteDNSRecordInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    #[serde(rename = "recordId")]
    pub record_id: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeleteDomainInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    #[serde(rename = "domainId")]
    pub domain_id: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeleteSshAuthorizedKeyByIdInput {
    /// SSH authorized key ID.
    #[serde(rename = "authorizedKeyId")]
    pub authorized_key_id: String,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeleteSshAuthorizedKeyInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// SSH User ID
    #[serde(rename = "sshUserId")]
    pub ssh_user_id: String,
}

/// An enumeration.
#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum DeployAppVersionsSortBy {
    #[default]
    #[serde(rename = "NEWEST")]
    Newest,
    #[serde(rename = "OLDEST")]
    Oldest,
}

/// An enumeration.
#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum DeployAppsSortBy {
    #[default]
    #[serde(rename = "MOST_ACTIVE")]
    MostActive,
    #[serde(rename = "NEWEST")]
    Newest,
    #[serde(rename = "OLDEST")]
    Oldest,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DeployViaAutobuildInput {
    #[serde(
        rename = "afterDeployCmd",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub after_deploy_cmd: Option<String>,
    /// If set, allows deploying a new version of an existing app.
    #[serde(
        rename = "allowExistingApp",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_existing_app: Option<bool>,
    #[serde(rename = "appId", default, skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    #[serde(rename = "appName", default, skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    /// Branch to deploy from. If no branch is specified, the default branch is used.
    #[serde(rename = "branch", default, skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    #[serde(rename = "buildCmd", default, skip_serializing_if = "Option::is_none")]
    pub build_cmd: Option<String>,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// Engine for the provisioned database. Defaults to MySQL.
    #[serde(rename = "dbEngine", default, skip_serializing_if = "Option::is_none")]
    pub db_engine: Option<DatabaseEngine>,
    /// Domains for this app
    #[serde(rename = "domains", default, skip_serializing_if = "Option::is_none")]
    pub domains: Option<Vec<Option<String>>>,
    #[serde(
        rename = "enableDatabase",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_database: Option<bool>,
    #[serde(rename = "envVars", default, skip_serializing_if = "Option::is_none")]
    pub env_vars: Option<Vec<Option<EnvVarInput>>>,
    #[serde(rename = "extraData", default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<AutobuildDeploymentExtraData>,
    #[serde(
        rename = "installCmd",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub install_cmd: Option<String>,
    /// Additional jobs to run in the deployment.
    #[serde(rename = "jobs", default, skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Vec<Option<JobDefinitionInput>>>,
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// If set, the app is managed by wasmer.
    #[serde(rename = "managed", default, skip_serializing_if = "Option::is_none")]
    pub managed: Option<bool>,
    #[serde(rename = "owner", default, skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    #[serde(rename = "params", default, skip_serializing_if = "Option::is_none")]
    pub params: Option<AutobuildDeploymentExtraData>,
    /// When the app should be perished
    #[serde(rename = "perishAt", default, skip_serializing_if = "Option::is_none")]
    pub perish_at: Option<String>,
    #[serde(
        rename = "presetName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub preset_name: Option<String>,
    /// Region to deploy the app
    #[serde(rename = "region", default, skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(rename = "repoUrl", default, skip_serializing_if = "Option::is_none")]
    pub repo_url: Option<String>,
    /// The root directory to build from (defaults to /)
    #[serde(rename = "rootDir", default, skip_serializing_if = "Option::is_none")]
    pub root_dir: Option<String>,
    #[serde(rename = "startCmd", default, skip_serializing_if = "Option::is_none")]
    pub start_cmd: Option<String>,
    #[serde(rename = "uploadUrl", default, skip_serializing_if = "Option::is_none")]
    pub upload_url: Option<String>,
    /// If set, deployment completion waits for screenshot generation.
    #[serde(
        rename = "waitForScreenshotGeneration",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub wait_for_screenshot_generation: Option<bool>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DisconnectGithubRepoFromAppInput {
    /// The ID of the App
    #[serde(rename = "appId")]
    pub app_id: String,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct EditSshUserInput {
    #[serde(
        rename = "authenticationMethods",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub authentication_methods: Option<Vec<Option<SshAuthenticationMethod>>>,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// SSH User ID
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "sftpRootFolder",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub sftp_root_folder: Option<String>,
    #[serde(rename = "username", default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct EnvVarInput {
    /// Whether the environment variable is available during builds.
    #[serde(rename = "build", default, skip_serializing_if = "Option::is_none")]
    pub build: Option<bool>,
    /// Name of the environment variable.
    #[serde(rename = "name")]
    pub name: String,
    /// Whether the environment variable is available at runtime.
    #[serde(rename = "runtime", default, skip_serializing_if = "Option::is_none")]
    pub runtime: Option<bool>,
    /// Whether the environment variable value should be hidden from GraphQL.
    #[serde(rename = "sensitive", default, skip_serializing_if = "Option::is_none")]
    pub sensitive: Option<bool>,
    /// Value of the environment variable.
    #[serde(rename = "value")]
    pub value: String,
}

/// Execute (package/command) target for an `Api`-sourced cronjob.
///
/// On update, providing an `execute` object replaces the whole execute target.
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct ExecuteCronJobTargetInput {
    /// CLI arguments as a JSON array.
    #[serde(rename = "cliArgs", default, skip_serializing_if = "Option::is_none")]
    pub cli_args: Option<serde_json::Value>,
    #[serde(rename = "command", default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    /// Environment variables as a JSON object.
    #[serde(rename = "env", default, skip_serializing_if = "Option::is_none")]
    pub env: Option<serde_json::Value>,
    #[serde(
        rename = "packageName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub package_name: Option<String>,
}

/// Fetch (HTTP) target for an `Api`-sourced cronjob.
///
/// On update, providing a `fetch` object replaces the whole fetch target of the
/// cronjob; individual fields left unset fall back to their defaults.
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FetchCronJobTargetInput {
    #[serde(rename = "body", default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(
        rename = "expectBodyIncludes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub expect_body_includes: Option<String>,
    #[serde(
        rename = "expectBodyRegex",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub expect_body_regex: Option<String>,
    /// Accepted status codes as a JSON array.
    #[serde(
        rename = "expectStatusCodes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub expect_status_codes: Option<serde_json::Value>,
    /// Request headers as a JSON object.
    #[serde(rename = "headers", default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<serde_json::Value>,
    /// HTTP method. Defaults to `GET`.
    #[serde(rename = "method", default, skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    #[serde(rename = "path")]
    pub path: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct GenerateSshTokenInput {
    #[serde(rename = "appId", default, skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum HTTPRedirectType {
    #[default]
    #[serde(rename = "PERMANENT_MOVED")]
    PermanentMoved,
    #[serde(rename = "PERMANENT_REDIRECT")]
    PermanentRedirect,
    #[serde(rename = "TEMPORARY_FOUND")]
    TemporaryFound,
    #[serde(rename = "TEMPORARY_REDIRECT")]
    TemporaryRedirect,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct JobDefinitionInput {
    #[serde(rename = "cliArgs", default, skip_serializing_if = "Option::is_none")]
    pub cli_args: Option<Vec<Option<String>>>,
    /// Command to run the job
    #[serde(rename = "command")]
    pub command: String,
    #[serde(rename = "env", default, skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<Option<String>>>,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "package", default, skip_serializing_if = "Option::is_none")]
    pub package: Option<String>,
    /// Humanfriendly timeout definition. e.g. 10m, 1h
    #[serde(rename = "timeout", default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

/// An enumeration.
#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum LogStream {
    #[default]
    #[serde(rename = "RUNTIME")]
    Runtime,
    #[serde(rename = "STDERR")]
    Stderr,
    #[serde(rename = "STDOUT")]
    Stdout,
}

/// Groupings for metrics
#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum MetricGrouping {
    #[default]
    #[serde(rename = "BY_5_MINUTES")]
    By5Minutes,
    #[serde(rename = "BY_15_MINUTES")]
    By15Minutes,
    #[serde(rename = "BY_DAY")]
    ByDay,
    #[serde(rename = "BY_HOUR")]
    ByHour,
    #[serde(rename = "BY_WEEK")]
    ByWeek,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum PackageOrderBy {
    #[default]
    #[serde(rename = "ALPHABETICALLY")]
    Alphabetically,
    #[serde(rename = "CREATED_DATE")]
    CreatedDate,
    #[serde(rename = "PUBLISHED_DATE")]
    PublishedDate,
    #[serde(rename = "SIZE")]
    Size,
    #[serde(rename = "TOTAL_DOWNLOADS")]
    TotalDownloads,
    #[serde(rename = "TOTAL_LIKES")]
    TotalLikes,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct PackagesFilter {
    #[serde(rename = "count", default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Filter packages created after this date.
    #[serde(
        rename = "createdAfter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub created_after: Option<String>,
    /// Filter packages created before this date.
    #[serde(
        rename = "createdBefore",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub created_before: Option<String>,
    /// Filter packages by being curated.
    #[serde(rename = "curated", default, skip_serializing_if = "Option::is_none")]
    pub curated: Option<bool>,
    /// Filter packages by deployable status.
    #[serde(
        rename = "deployable",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub deployable: Option<bool>,
    /// Filter packages by download count.
    #[serde(rename = "downloads", default, skip_serializing_if = "Option::is_none")]
    pub downloads: Option<CountFilter>,
    /// Filter packages by having bindings.
    #[serde(
        rename = "hasBindings",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_bindings: Option<bool>,
    /// Filter packages by having commands.
    #[serde(
        rename = "hasCommands",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_commands: Option<bool>,
    /// Filter packages by being standalone.
    #[serde(
        rename = "isStandalone",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_standalone: Option<bool>,
    /// Filter packages with version published after this date.
    #[serde(
        rename = "lastPublishedAfter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_published_after: Option<String>,
    /// Filter packages with version published before this date.
    #[serde(
        rename = "lastPublishedBefore",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_published_before: Option<String>,
    /// Filter packages by license.
    #[serde(rename = "license", default, skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    /// Filter packages by like count.
    #[serde(rename = "likes", default, skip_serializing_if = "Option::is_none")]
    pub likes: Option<CountFilter>,
    /// Order packages by field.
    #[serde(rename = "orderBy", default, skip_serializing_if = "Option::is_none")]
    pub order_by: Option<PackageOrderBy>,
    /// Filter packages by owner.
    #[serde(rename = "owner", default, skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// Filter packages by publish date.
    #[serde(
        rename = "publishDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub publish_date: Option<SearchPublishDate>,
    /// Filter packages by published by.
    #[serde(
        rename = "publishedBy",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub published_by: Option<String>,
    /// Filter packages by size.
    #[serde(rename = "size", default, skip_serializing_if = "Option::is_none")]
    pub size: Option<CountFilter>,
    #[serde(rename = "sortBy", default, skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<SearchOrderSort>,
    /// Filter packages by interface.
    #[serde(
        rename = "withInterfaces",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub with_interfaces: Option<Vec<Option<String>>>,
}

/// An enumeration.
#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum RecordKind {
    #[default]
    #[serde(rename = "A")]
    A,
    #[serde(rename = "AAAA")]
    Aaaa,
    #[serde(rename = "CAA")]
    Caa,
    #[serde(rename = "CNAME")]
    Cname,
    #[serde(rename = "DNAME")]
    Dname,
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "NS")]
    Ns,
    #[serde(rename = "PTR")]
    Ptr,
    #[serde(rename = "SOA")]
    Soa,
    #[serde(rename = "SRV")]
    Srv,
    #[serde(rename = "SSHFP")]
    Sshfp,
    #[serde(rename = "TXT")]
    Txt,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct RegisterDomainInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    #[serde(
        rename = "importRecords",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub import_records: Option<bool>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace", default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "ownerId", default, skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct RevealSshUserPasswordInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// SSH User ID
    #[serde(rename = "sshUserId")]
    pub ssh_user_id: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct RotateCredentialsForAppDBInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// App Database ID
    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct RotateSshUserPasswordInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// SSH User ID
    #[serde(rename = "sshUserId")]
    pub ssh_user_id: String,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum SearchOrderSort {
    #[default]
    #[serde(rename = "ASC")]
    Asc,
    #[serde(rename = "DESC")]
    Desc,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum SearchPublishDate {
    #[default]
    #[serde(rename = "LAST_DAY")]
    LastDay,
    #[serde(rename = "LAST_MONTH")]
    LastMonth,
    #[serde(rename = "LAST_WEEK")]
    LastWeek,
    #[serde(rename = "LAST_YEAR")]
    LastYear,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct SendAppEmailInput {
    #[serde(rename = "appId")]
    pub app_id: String,
    #[serde(rename = "bcc", default, skip_serializing_if = "Option::is_none")]
    pub bcc: Option<Vec<String>>,
    #[serde(rename = "cc", default, skip_serializing_if = "Option::is_none")]
    pub cc: Option<Vec<String>>,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    #[serde(
        rename = "fromAddress",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub from_address: Option<String>,
    #[serde(
        rename = "fromEmailId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub from_email_id: Option<String>,
    #[serde(rename = "htmlBody", default, skip_serializing_if = "Option::is_none")]
    pub html_body: Option<String>,
    #[serde(
        rename = "rawMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub raw_message: Option<serde_json::Value>,
    #[serde(rename = "replyTo", default, skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<String>,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "textBody", default, skip_serializing_if = "Option::is_none")]
    pub text_body: Option<String>,
    #[serde(rename = "to")]
    pub to: Vec<String>,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum SshAuthenticationMethod {
    #[default]
    #[serde(rename = "PASSWORD")]
    Password,
    #[serde(rename = "PUBLIC_KEY")]
    PublicKey,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct ToggleSshServerInput {
    /// App ID
    #[serde(rename = "appId")]
    pub app_id: String,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

/// Update an existing `Api`-sourced unified cronjob.
///
/// Absent fields are left unchanged (partial patch). The nullable duration /
/// retry fields are tri-state: absent = keep, explicit `null` = clear. The
/// cronjob `kind` is immutable, so a provided `fetch` / `execute` target must
/// match the existing kind and replaces that target wholesale.
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct UpdateCronJobInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// CronJob ID.
    #[serde(rename = "cronJobId")]
    pub cron_job_id: String,
    #[serde(rename = "enabled", default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "execute", default, skip_serializing_if = "Option::is_none")]
    pub execute: Option<ExecuteCronJobTargetInput>,
    #[serde(rename = "fetch", default, skip_serializing_if = "Option::is_none")]
    pub fetch: Option<FetchCronJobTargetInput>,
    #[serde(
        rename = "maxRetries",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_retries: Option<i32>,
    #[serde(
        rename = "maxScheduleDrift",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_schedule_drift: Option<String>,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "schedule", default, skip_serializing_if = "Option::is_none")]
    pub schedule: Option<String>,
    #[serde(rename = "timeout", default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct UpdateDNSRecordsInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// ID of the DNS domain whose records should be changed.
    #[serde(rename = "domainId")]
    pub domain_id: String,
    #[serde(rename = "records", default, skip_serializing_if = "Option::is_none")]
    pub records: Option<Vec<Option<DNSRecordUpdate>>>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct UpdateGithubRepoAppConnectionInput {
    /// The app whose GitHub repo connection should be updated.
    #[serde(rename = "appId", default, skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// The ID of the GithubRepoConnection.
    ///
    /// Deprecated for app-scoped SDK usage; use `appId` instead.
    #[serde(
        rename = "connectionId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub connection_id: Option<String>,
    /// Optional deploy branch for the app-scoped GitHub repo connection.
    #[serde(
        rename = "deployBranch",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub deploy_branch: Option<String>,
    #[serde(
        rename = "deploymentStatusEvents",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub deployment_status_events: Option<bool>,
    #[serde(
        rename = "pullRequestComments",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pull_request_comments: Option<bool>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct UpdateVolumeInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// App Volume ID
    #[serde(rename = "id")]
    pub id: String,
    /// Volume max size in bytes
    #[serde(
        rename = "maxSizeBytes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_size_bytes: Option<i64>,
    /// Volume mount path
    #[serde(rename = "mountPath", default, skip_serializing_if = "Option::is_none")]
    pub mount_path: Option<String>,
    /// Whether to redeploy the active app version after workload changes
    #[serde(
        rename = "redeployApp",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub redeploy_app: Option<bool>,
    /// Whether the S3 endpoint is enabled
    #[serde(rename = "s3Enabled", default, skip_serializing_if = "Option::is_none")]
    pub s3_enabled: Option<bool>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct UpsertAppDomainInput {
    /// ID of the app onto which to add secrets.
    #[serde(rename = "appId")]
    pub app_id: String,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// ID of the domain to upsert.
    #[serde(rename = "id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Whether this domain should become the app's selected default domain.
    #[serde(rename = "isDefault", default, skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    /// Name of the secret.
    #[serde(rename = "name")]
    pub name: String,
    /// Redirection rules for this domain
    #[serde(
        rename = "redirection",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub redirection: Option<AppDomainRedirectRules>,
    /// Wait for the domain to become available before returning.
    #[serde(rename = "wait", default, skip_serializing_if = "Option::is_none")]
    pub wait: Option<bool>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct UpsertDNSRecordInput {
    #[serde(rename = "caa", default, skip_serializing_if = "Option::is_none")]
    pub caa: Option<DNSCAAExtraInput>,
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    #[serde(rename = "domainId")]
    pub domain_id: String,
    #[serde(rename = "kind")]
    pub kind: RecordKind,
    #[serde(rename = "mx", default, skip_serializing_if = "Option::is_none")]
    pub mx: Option<DNSMXExtraInput>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "recordId", default, skip_serializing_if = "Option::is_none")]
    pub record_id: Option<String>,
    #[serde(rename = "soa", default, skip_serializing_if = "Option::is_none")]
    pub soa: Option<DNSSOAExtraInput>,
    #[serde(rename = "srv", default, skip_serializing_if = "Option::is_none")]
    pub srv: Option<DNSSRVExtraInput>,
    #[serde(rename = "sshfp", default, skip_serializing_if = "Option::is_none")]
    pub sshfp: Option<DNSSSHFPExtraInput>,
    #[serde(rename = "ttl", default, skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    #[serde(rename = "value")]
    pub value: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct UpsertDomainFromZoneFileInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    #[serde(
        rename = "deleteMissingRecords",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub delete_missing_records: Option<bool>,
    #[serde(rename = "zoneFile")]
    pub zone_file: String,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub enum VerificationKind {
    #[default]
    #[serde(rename = "DEEP")]
    Deep,
    #[serde(rename = "QUICK")]
    Quick,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct VerifyAppDomainInput {
    #[serde(
        rename = "clientMutationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub client_mutation_id: Option<String>,
    /// The ID of the domain to verify
    #[serde(rename = "domainId")]
    pub domain_id: String,
    /// Specify how to verify the domain
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<VerificationKind>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct WordpressDeploymentExtraData {
    #[serde(rename = "adminEmail")]
    pub admin_email: String,
    #[serde(rename = "adminPassword")]
    pub admin_password: String,
    #[serde(rename = "adminUsername")]
    pub admin_username: String,
    #[serde(rename = "language", default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "siteName")]
    pub site_name: String,
    #[serde(rename = "theme", default, skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
}
