//! GraphQL operations shared with the other StackMachine SDKs.
// Generated by tools/generate.mjs. Do not edit by hand.

pub const ADD_SSH_AUTHORIZED_KEY_MUTATION: &str =
    include_str!("../graphql/add_ssh_authorized_key_mutation.graphql");
pub const AUTOBUILD_MUTATION: &str = include_str!("../graphql/autobuild_mutation.graphql");
pub const AUTOBUILD_SUBSCRIPTION: &str = include_str!("../graphql/autobuild_subscription.graphql");
pub const CONFIGURE_APP_CDN_CACHE_MUTATION: &str =
    include_str!("../graphql/configure_app_cdn_cache_mutation.graphql");
pub const CONNECT_GITHUB_REPO_TO_APP_MUTATION: &str =
    include_str!("../graphql/connect_github_repo_to_app_mutation.graphql");
pub const CREATE_APP_DATABASE_MUTATION: &str =
    include_str!("../graphql/create_app_database_mutation.graphql");
pub const CREATE_APP_VOLUME_MUTATION: &str =
    include_str!("../graphql/create_app_volume_mutation.graphql");
pub const CREATE_CRON_JOB_MUTATION: &str =
    include_str!("../graphql/create_cron_job_mutation.graphql");
pub const CREATE_DATABASE_AND_LINK_TO_APP_MUTATION: &str =
    include_str!("../graphql/create_database_and_link_to_app_mutation.graphql");
pub const DELETE_APP_DATABASE_MUTATION: &str =
    include_str!("../graphql/delete_app_database_mutation.graphql");
pub const DELETE_APP_DOMAIN_MUTATION: &str =
    include_str!("../graphql/delete_app_domain_mutation.graphql");
pub const DELETE_APP_MUTATION: &str = include_str!("../graphql/delete_app_mutation.graphql");
pub const DELETE_APP_VOLUME_MUTATION: &str =
    include_str!("../graphql/delete_app_volume_mutation.graphql");
pub const DELETE_CRON_JOB_MUTATION: &str =
    include_str!("../graphql/delete_cron_job_mutation.graphql");
pub const DELETE_DNS_DOMAIN_MUTATION: &str =
    include_str!("../graphql/delete_dns_domain_mutation.graphql");
pub const DELETE_DNS_RECORD_MUTATION: &str =
    include_str!("../graphql/delete_dns_record_mutation.graphql");
pub const DELETE_SSH_AUTHORIZED_KEY_BY_ID_MUTATION: &str =
    include_str!("../graphql/delete_ssh_authorized_key_by_id_mutation.graphql");
pub const DELETE_SSH_AUTHORIZED_KEY_MUTATION: &str =
    include_str!("../graphql/delete_ssh_authorized_key_mutation.graphql");
pub const DISCONNECT_GITHUB_REPO_FROM_APP_MUTATION: &str =
    include_str!("../graphql/disconnect_github_repo_from_app_mutation.graphql");
pub const EDIT_SSH_USER_MUTATION: &str = include_str!("../graphql/edit_ssh_user_mutation.graphql");
pub const GENERATE_SSH_TOKEN_MUTATION: &str =
    include_str!("../graphql/generate_ssh_token_mutation.graphql");
pub const GET_APP_ALIASES_QUERY: &str = include_str!("../graphql/get_app_aliases_query.graphql");
pub const GET_APP_BY_ID_QUERY: &str = include_str!("../graphql/get_app_by_id_query.graphql");
pub const GET_APP_BY_NAME_QUERY: &str = include_str!("../graphql/get_app_by_name_query.graphql");
pub const GET_APP_CACHE_QUERY: &str = include_str!("../graphql/get_app_cache_query.graphql");
pub const GET_APP_GIT_CONNECTION_QUERY: &str =
    include_str!("../graphql/get_app_git_connection_query.graphql");
pub const GET_APP_GIT_CONNECTIONS_QUERY: &str =
    include_str!("../graphql/get_app_git_connections_query.graphql");
pub const GET_APP_LOGS_QUERY: &str = include_str!("../graphql/get_app_logs_query.graphql");
pub const GET_APP_SSH_SERVER_QUERY: &str =
    include_str!("../graphql/get_app_ssh_server_query.graphql");
pub const GET_APP_SSH_SERVERS_QUERY: &str =
    include_str!("../graphql/get_app_ssh_servers_query.graphql");
pub const GET_APP_SSH_USERS_QUERY: &str =
    include_str!("../graphql/get_app_ssh_users_query.graphql");
pub const GET_APPS_BY_IDS_QUERY: &str = include_str!("../graphql/get_apps_by_ids_query.graphql");
pub const GET_CRON_JOBS_BY_IDS_QUERY: &str =
    include_str!("../graphql/get_cron_jobs_by_ids_query.graphql");
pub const GET_DEPLOYMENT_STATUS_QUERY: &str =
    include_str!("../graphql/get_deployment_status_query.graphql");
pub const GET_DNS_DOMAIN_BY_NAME_QUERY: &str =
    include_str!("../graphql/get_dns_domain_by_name_query.graphql");
pub const GET_DNS_DOMAINS_QUERY: &str = include_str!("../graphql/get_dns_domains_query.graphql");
pub const GET_DNS_RECORDS_QUERY: &str = include_str!("../graphql/get_dns_records_query.graphql");
pub const GET_GITHUB_REPO_UPDATE_TARGET_QUERY: &str =
    include_str!("../graphql/get_github_repo_update_target_query.graphql");
pub const GET_SSH_AUTHORIZED_KEYS_QUERY: &str =
    include_str!("../graphql/get_ssh_authorized_keys_query.graphql");
pub const GET_SSH_USER_BY_ID_QUERY: &str =
    include_str!("../graphql/get_ssh_user_by_id_query.graphql");
pub const GET_SSH_USERS_BY_IDS_QUERY: &str =
    include_str!("../graphql/get_ssh_users_by_ids_query.graphql");
pub const LIST_APP_CRON_JOBS_QUERY: &str =
    include_str!("../graphql/list_app_cron_jobs_query.graphql");
pub const LIST_APP_DATABASES_QUERY: &str =
    include_str!("../graphql/list_app_databases_query.graphql");
pub const LIST_APP_DOMAINS_QUERY: &str = include_str!("../graphql/list_app_domains_query.graphql");
pub const LIST_APP_VERSIONS_QUERY: &str =
    include_str!("../graphql/list_app_versions_query.graphql");
pub const LIST_APP_VOLUMES_QUERY: &str = include_str!("../graphql/list_app_volumes_query.graphql");
pub const LIST_APPS_QUERY: &str = include_str!("../graphql/list_apps_query.graphql");
pub const LIST_DNS_DOMAINS_QUERY: &str = include_str!("../graphql/list_dns_domains_query.graphql");
pub const LIST_DNS_RECORDS_CONNECTION_QUERY: &str =
    include_str!("../graphql/list_dns_records_connection_query.graphql");
pub const LIST_DNS_RECORDS_QUERY: &str = include_str!("../graphql/list_dns_records_query.graphql");
pub const LIST_RECEIVED_EMAILS_QUERY: &str =
    include_str!("../graphql/list_received_emails_query.graphql");
pub const LIST_SENT_EMAILS_QUERY: &str = include_str!("../graphql/list_sent_emails_query.graphql");
pub const PURGE_APP_CDN_CACHE_MUTATION: &str =
    include_str!("../graphql/purge_app_cdn_cache_mutation.graphql");
pub const REGISTER_DNS_DOMAIN_MUTATION: &str =
    include_str!("../graphql/register_dns_domain_mutation.graphql");
pub const REVEAL_SSH_USER_PASSWORD_MUTATION: &str =
    include_str!("../graphql/reveal_ssh_user_password_mutation.graphql");
pub const ROTATE_APP_DATABASE_CREDENTIALS_MUTATION: &str =
    include_str!("../graphql/rotate_app_database_credentials_mutation.graphql");
pub const ROTATE_SSH_USER_PASSWORD_MUTATION: &str =
    include_str!("../graphql/rotate_ssh_user_password_mutation.graphql");
pub const SEARCH_PACKAGES_QUERY: &str = include_str!("../graphql/search_packages_query.graphql");
pub const SEND_APP_EMAIL_MUTATION: &str =
    include_str!("../graphql/send_app_email_mutation.graphql");
pub const TOGGLE_SSH_SERVER_MUTATION: &str =
    include_str!("../graphql/toggle_ssh_server_mutation.graphql");
pub const UPDATE_CRON_JOB_MUTATION: &str =
    include_str!("../graphql/update_cron_job_mutation.graphql");
pub const UPDATE_DNS_RECORDS_MUTATION: &str =
    include_str!("../graphql/update_dns_records_mutation.graphql");
pub const UPDATE_GITHUB_REPO_CONNECTION_MUTATION: &str =
    include_str!("../graphql/update_github_repo_connection_mutation.graphql");
pub const UPDATE_VOLUME_MUTATION: &str = include_str!("../graphql/update_volume_mutation.graphql");
pub const UPLOAD_QUERY: &str = include_str!("../graphql/upload_query.graphql");
pub const UPSERT_APP_DOMAIN_MUTATION: &str =
    include_str!("../graphql/upsert_app_domain_mutation.graphql");
pub const UPSERT_DNS_DOMAIN_FROM_ZONE_FILE_MUTATION: &str =
    include_str!("../graphql/upsert_dns_domain_from_zone_file_mutation.graphql");
pub const UPSERT_DNS_RECORD_MUTATION: &str =
    include_str!("../graphql/upsert_dns_record_mutation.graphql");
pub const USAGE_APP_METRICS_QUERY: &str =
    include_str!("../graphql/usage_app_metrics_query.graphql");
pub const USAGE_OWNER_METRICS_QUERY: &str =
    include_str!("../graphql/usage_owner_metrics_query.graphql");
pub const USAGE_VIEWER_METRICS_QUERY: &str =
    include_str!("../graphql/usage_viewer_metrics_query.graphql");
pub const VERIFY_APP_DOMAIN_MUTATION: &str =
    include_str!("../graphql/verify_app_domain_mutation.graphql");
pub const VIEWER_QUERY: &str = include_str!("../graphql/viewer_query.graphql");
