query srcListDNSDomainsQuery(
  $owner: ID
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  getAllDomains(
    ownerId: $owner
    first: $first
    after: $after
    last: $last
    before: $before
  ) {
    edges {
      cursor
      node {

id
name
slug
zoneFile
delegationStatus
nameservers
lastCheckedAt
verifiedAt
deletedAt
createdAt
updatedAt
owner {

__typename
globalId
globalName
isPro
... on Namespace {
  id
  name
  displayName
}
... on User {
  id
  username
}

}

      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      endCursor
      startCursor
    }
    totalCount
  }
}
