query srcListAppCronJobsQuery(
  $appId: ID!
  $first: Int
  $after: String
  $last: Int
  $before: String
  $kind: CronJobKind
  $sortBy: CronJobsSortBy
) {
  node(id: $appId) {
    ... on DeployApp {
      cronJobs(
        first: $first
        after: $after
        last: $last
        before: $before
        kind: $kind
        sortBy: $sortBy
      ) {
        edges {
          cursor
          node {

id
name
schedule
enabled
kind
source
isManaged
maxRetries
maxScheduleDrift
timeout
createdAt
updatedAt
target {
  __typename
  ... on ExecuteCronJobTarget {
    command
    cliArgs
    env
    packageName
  }
  ... on FetchCronJobTarget {
    path
    method
    headers
    body
    expectBodyIncludes
    expectBodyRegex
    expectStatusCodes
  }
}

          }
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          endCursor
          startCursor
        }
        totalCount
      }
    }
  }
}
